# Generated by Django 4.0.4 on 2022-05-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Title')),
                ('author', models.CharField(blank=True, max_length=50, verbose_name='Title')),
                ('upload_time', models.DateTimeField(unique=True)),
                ('content', models.TextField(verbose_name='content')),
            ],
        ),
        migrations.CreateModel(
            name='Mystery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Title')),
                ('author', models.CharField(blank=True, max_length=50, verbose_name='Title')),
                ('upload_time', models.DateTimeField(unique=True)),
                ('content', models.TextField(verbose_name='content')),
            ],
        ),
        migrations.CreateModel(
            name='Romance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Title')),
                ('author', models.CharField(blank=True, max_length=50, verbose_name='Title')),
                ('upload_time', models.DateTimeField(unique=True)),
                ('content', models.TextField(verbose_name='content')),
            ],
        ),
    ]
