# Generated by Django 4.0.4 on 2022-05-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disaster',
            name='author',
            field=models.CharField(blank=True, max_length=50, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='mystery',
            name='author',
            field=models.CharField(blank=True, max_length=50, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='romance',
            name='author',
            field=models.CharField(blank=True, max_length=50, verbose_name='Author'),
        ),
    ]
