# Generated by Django 4.0.4 on 2022-05-17 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_r_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='R_Comment',
        ),
    ]
