# Generated by Django 4.0.4 on 2022-05-17 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_r_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r_comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='R_comments', to='book.romance'),
        ),
    ]
