# Generated by Django 4.0.4 on 2022-05-17 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_hashtag_romance_hashtag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='romance',
        ),
    ]
