# Generated by Django 4.0.4 on 2022-05-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_rename_post_comment_romance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='romance',
            new_name='post',
        ),
    ]
