# Generated by Django 4.0.4 on 2022-05-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_m_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='mystery',
            name='hashtag',
            field=models.ManyToManyField(to='book.m_hashtag'),
        ),
    ]
