# Generated by Django 4.0.4 on 2022-05-21 17:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_m_hashtag_mystery_hashtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='D_HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='D_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='book.disaster')),
            ],
        ),
        migrations.AddField(
            model_name='disaster',
            name='hashtag',
            field=models.ManyToManyField(to='book.d_hashtag'),
        ),
    ]
