# Generated by Django 4.0.4 on 2022-05-24 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_romance_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='R_Comment',
        ),
    ]
