# Generated by Django 4.0.4 on 2022-05-21 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0002_d_hashtag_hashtag_m_hashtag_r_comment_m_comment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HashTag',
            new_name='R_HashTag',
        ),
    ]
