# Generated by Django 4.0.4 on 2022-05-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0003_rename_hashtag_r_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaster',
            name='hashtag',
            field=models.ManyToManyField(to='drama.d_hashtag'),
        ),
        migrations.AddField(
            model_name='mystery',
            name='hashtag',
            field=models.ManyToManyField(to='drama.m_hashtag'),
        ),
        migrations.AddField(
            model_name='romance',
            name='hashtag',
            field=models.ManyToManyField(to='drama.r_hashtag'),
        ),
    ]
