# Generated by Django 4.0.4 on 2022-05-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drama', '0004_disaster_hashtag_mystery_hashtag_romance_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='disaster',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='drama_photo'),
        ),
        migrations.AddField(
            model_name='mystery',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='drama_photo'),
        ),
        migrations.AddField(
            model_name='romance',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='drama_photo'),
        ),
    ]
