# Generated by Django 4.0.4 on 2022-06-02 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_age_customuser_star'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='star',
            new_name='age',
        ),
    ]
