# Generated by Django 4.0.4 on 2022-05-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=20, verbose_name='Country')),
                ('plate_name', models.CharField(blank=True, max_length=30, verbose_name='Plate')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='Title')),
                ('minutes', models.IntegerField(blank=True, verbose_name='Minutes')),
                ('upload_time', models.DateTimeField(unique=True)),
                ('content', models.TextField(verbose_name='Content')),
            ],
        ),
    ]
