# Generated by Django 4.0.4 on 2022-05-03 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_remove_posting_upload_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 3, 20, 36, 18, 101693)),
        ),
    ]
