# Generated by Django 4.0.3 on 2022-05-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='upload_time',
            field=models.DateTimeField(),
        ),
    ]
