# Generated by Django 4.0.3 on 2022-05-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='hashtags',
            field=models.ManyToManyField(to='main.hashtag'),
        ),
    ]
