# Generated by Django 4.0.4 on 2022-05-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_hashtag_remove_posting_content_posting_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='body',
            field=models.TextField(default='', null=True),
        ),
    ]
