# Generated by Django 4.0.4 on 2022-05-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deutsch', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='posting',
            name='hashtag',
            field=models.ManyToManyField(to='Deutsch.hashtag'),
        ),
    ]
