# Generated by Django 4.0.4 on 2022-05-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deutsch', '0003_hashtag_posting_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='post_photo'),
        ),
    ]
